[package]
name = "qr_encode_entry_function"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.11.2"
qr_encoder = { path = "../qr_encoder" }
serde = { version = "1.0.202", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
