[workspace]
resolver = "2"
members = [
  "crates/qr_aws",
  "crates/qr_cli",
  "crates/qr_encode_entry_function",
  "crates/qr_encode_result_function",
  "crates/qr_encoder",
  "crates/qr_error",
  "crates/qr_result_web_socket_connect_function",
]
