[package]
name = "qr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
qr_encoder = { path = "crates/qr_encoder" }

[workspace]
members = ["crates/qr_encoder"]
