version = 0.1

[default]
[default.global.parameters]
stack_name = "qr-backend-stage"

[default.build.parameters]
cached = true
parallel = true
beta_features = true
parameter_overrides = "Environment=stage"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "qr-backend/stage"
region = "eu-central-1"
image_repositories = []
parameter_overrides = "Environment=stage"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
beta_features = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.global.parameters]
stack_name = "qr-backend-prod"

[prod.build.parameters]
cached = true
parallel = true
beta_features = true
parameter_overrides = "Environment=prod"

[prod.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "qr-backend/prod"
region = "eu-central-1"
image_repositories = []
parameter_overrides = "Environment=prod"

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true
beta_features = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"
