[package]
name = "qr_error"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-apigatewaymanagement = "1.31.0"
aws-sdk-dynamodb = "1.34.0"
aws-sdk-sqs = "1.27.0"
serde_json = "1.0.117"
thiserror = "1.0.61"
