[package]
name = "qr_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["json", "blocking"] }
