[package]
name = "qr_encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
itertools = "0.12.1"
qr_error = { path = "../qr_error" }
serde = { version = "1.0.202", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
