name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: x86_64

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Backend
        run: sam build

      - name: Deploy Backend
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Retrieve QR Encode API URL
        run: |
          QR_ENCODE_API_URL=$(sam list stack-outputs --output json | jq '.[] | select(.OutputKey == "QrEncodeApiUrl") | .OutputValue')
          echo "QR_ENCODE_API_URL=$QR_ENCODE_API_URL" >> $GITHUB_ENV

      - name: Print QR Encode API URL
        run: echo "QR encode API URL - ${{ env.QR_ENCODE_API_URL }}"
      
      - name: Save QR Encode API URL
        run: echo "${{ env.QR_ENCODE_API_URL }}" > qr_encode_api_url.txt

      - name: Upload QR Encode API URL
        uses: actions/upload-artifact@v4
        with:
          name: qr_encode_api_url
          path: qr_encode_api_url.txt

  build-upload-frontend:
    needs: build-deploy-backend

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Download QR Encode API URL
        uses: actions/download-artifact@v4
        with:
          name: qr_encode_api_url

      - name: Read QR Encode API URL into environment
        run: |
          QR_ENCODE_API_URL=$(cat qr_encode_api_url.txt)
          echo "QR_ENCODE_API_URL=$QR_ENCODE_API_URL" >> $GITHUB_ENV

      - name: Build CLI Frontend
        env:
          QR_ENCODE_API_URL: ${{ env.QR_ENCODE_API_URL }}
        run: cargo build -p qr_cli --release

      - name: Upload CLI Frontend Artifact for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: qr_cli
          path: target/release/qr_cli_linux

      - name: Upload CLI Frontend Artifact for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: qr_cli
          path: target/release/qr_cli_macos
